[workspace]
members = [
    "sherpa-rs-next",
    "sherpa-rs-next-macro",
    "examples/asr-online",
    "examples/asr-offline",
    "examples/tts-offline",
    "examples/asr-app/src-tauri",
]
resolver = "2"
