[package]
name = "simulate-streaming"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.17.1"
colored = "3.0.0"
sherpa-rs-next = { path = "../../sherpa-rs-next" }
anyhow = "1.0"
ctrlc = "3.4.1"
